apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: native
          image: lutwrld/lut-config-server:dev-1.0.0
          name: config-server
          ports:
            - containerPort: 8888
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
